# Generated by Django 3.2.3 on 2021-05-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=254)),
                ('birthdate', models.DateField()),
                ('email', models.CharField(max_length=254)),
                ('selfdesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('properties', models.CharField(max_length=254)),
                ('instructions', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CookSpot.user')),
            ],
        ),
        migrations.CreateModel(
            name='Meets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('date', models.DateField()),
                ('desc', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CookSpot.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CookSpot.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('amount', models.CharField(max_length=254)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CookSpot.recipe')),
            ],
        ),
    ]
