# Generated by Django 3.2.3 on 2021-06-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookSpot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='properties',
            new_name='cookingtime',
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(default=40, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=0, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparationtime',
            field=models.CharField(default=30, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.CharField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
