# Generated by Django 3.2.3 on 2021-06-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookSpot', '0003_remove_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='A wonderful recipe'),
            preserve_default=False,
        ),
    ]
