# Generated by Django 3.2.3 on 2021-06-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookSpot', '0004_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
