# Generated by Django 3.2.1 on 2021-06-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookSpot', '0008_auto_20210605_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='imageURL',
            field=models.URLField(default=''),
        ),
    ]
