# Generated by Django 3.2.1 on 2021-06-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CookSpot', '0012_profile'),
    ]

    operations = [
    ]
