# Generated by Django 3.2.3 on 2021-06-30 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CookSpot', '0014_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='meets',
            name='maximumparticipants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meets',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='fromuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='givenratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='touser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gottenratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
