# Generated by Django 3.2.3 on 2021-07-01 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CookSpot', '0015_auto_20210630_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='rating',
        ),
        migrations.AlterField(
            model_name='meets',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='fromuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giveninvites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='meet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CookSpot.meets'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='touser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gotteninvites', to=settings.AUTH_USER_MODEL),
        ),
    ]
