# Generated by Django 3.2.3 on 2021-07-01 09:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CookSpot', '0016_auto_20210701_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrating',
            name='fromuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='givenratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='meet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CookSpot.meets'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='touser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gottenratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giveninvites', to=settings.AUTH_USER_MODEL)),
                ('meet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CookSpot.meets')),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gotteninvites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
