# Generated by Django 3.2.5 on 2021-07-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CookSpot', '0021_alter_favourite_cook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='cook',
            new_name='cooknew',
        ),
    ]
