# Generated by Django 3.2.5 on 2021-07-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CookSpot', '0022_rename_cook_favourite_cooknew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='cooknew',
        ),
    ]
