# Generated by Django 3.2.5 on 2021-07-04 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CookSpot', '0023_remove_favourite_cooknew'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='cookfav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favcook', to=settings.AUTH_USER_MODEL),
        ),
    ]
