# Generated by Django 3.2.2 on 2021-07-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookSpot', '0024_favourite_cookfav'),
    ]

    operations = [
        migrations.AddField(
            model_name='meets',
            name='location',
            field=models.CharField(default='my place', max_length=254),
            preserve_default=False,
        ),
    ]
