# Generated by Django 3.2.2 on 2021-07-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookSpot', '0025_meets_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='measurement',
            field=models.CharField(default='g', max_length=254),
            preserve_default=False,
        ),
    ]
