# Generated by Django 3.2.1 on 2021-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookSpot', '0025_alter_userrating_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
