# Generated by Django 3.2.2 on 2021-07-21 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CookSpot', '0026_ingredients_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chosenuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
