# Generated by Django 3.2.1 on 2021-07-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CookSpot', '0026_recipe_ingredients_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients_amount',
        ),
    ]
