# Generated by Django 3.2.2 on 2021-07-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CookSpot', '0027_ingredients_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favrecipe', to='CookSpot.recipe'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='meet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CookSpot.meets'),
        ),
    ]
