# Generated by Django 3.2.3 on 2021-07-22 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CookSpot', '0029_ingredients_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='meet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CookSpot.meets'),
        ),
    ]
